name: ifms
description: A new Flutter project.
version: 1.0.0

environment:
  sdk:  '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Base
  cupertino_icons: ^1.0.8
  nb_utils: ^7.0.4
  intl: ^0.19.0
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  permission_handler: ^11.4.0
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  country_code_picker: ^3.0.0
  percent_indicator: ^4.2.3
  quickalert: ^1.1.0
  geolocator: ^13.0.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  mapbox_maps_flutter: ^2.6.0
  pin_code_fields: ^8.0.1
  signature: ^6.0.0
  image_picker: ^1.1.2
  


dependency_overrides:
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  http: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.6.1
  build_runner: ^2.4.12
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true

  assets:
    - images/

